# Deployment.yaml.template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b31af60b-9d32-4e58-b8e5-bd19236fec85-nodejs-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: AWS ECR/nodejs-image:latest
        ports:
        - containerPort: 3000
