version: 1

before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin

archives:
- id: binaries
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
  - scripts/**
  - templates/**


changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"

brews:
- name: multims
  description: "How engineers learn about CLIs"
  homepage: "https://github.com/JACKT72xp/cli"
  tap:
    owner: JACKT72xp
    name: homebrew-cli
  commit_author:
    name: JACKT72xp
    email: jackt72xp@gmail.com
  folder: Formula
  install: |
    bin.install "multims"
    (etc/"multims").mkpath
    (etc/"multims/templates").install Dir["templates/*"]
    (pkgshare/"multims/scripts").mkpath
    (pkgshare/"multims/scripts").install Dir["scripts/*"]
  caveats: |
    Templates are located in #{etc/"multims/templates"}.
    Scripts are located in #{pkgshare/"multims/scripts"}.

