version: 1

before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin

archives:
- id: tar
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip

- id: custom
  name_template: "{{ .Binary }}_{{ .Arch }}"
  files:
  - scripts/**
  - templates/**


changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
