version: 1

before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin

archives:
- id: binaries
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
  files:
  - scripts/**
  - templates/**


changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"

brews:
- name: name
  description: How engineers learn about CLIs
  homepage: https://github.com/JACKT72xp/cli
  tap:
    owner: JACKT72xp
    name: homebrew-cli
  commit_author:
    name: github_handle
    email: jackt72xp@gmail.com
  folder: Formula
