apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    argocd.argoproj.io/instance: konnex-test-https-gateway
  name: konnex-test-https-gateway-ingress
  namespace: konnex-test
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - kyiv-test.konnex.cariad.digital 
  rules:
  - host: kyiv-test.konnex.cariad.digital
    http:
      paths:
      - backend:
          service:
            name: konnex-test-https-gateway-service
            port:
              number: 8080
        path: /
        pathType: Prefix
