apiVersion: v1
kind: Service
metadata:
  labels:
    app: openebs-cstor-admission-server
  name: openebs-cstor-admission-server
  namespace: storage
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: openebs-cstor-admission-server
  type: ClusterIP
