apiVersion: v1
kind: Pod
metadata:
  name: rsync-pod
spec:
  containers:
  - name: rsync-container
    image: alpinelinux/rsyncd:latest
    command: ["rsync", "-avz", "--delete", "/opt/code/", "/home/"]
    volumeMounts:
    - name: code-volume
      mountPath: /opt/code
  volumes:
  - name: code-volume
    hostPath:
      path: /Volumes/DataJack/Jack/hello_nodejs

