apiVersion: v1
kind: Pod
metadata:
  name: rsync-pod
spec:
  restartPolicy: Never
  containers:
  - name: rsync-container
    image: alpine:latest
    command: 
      - "/bin/sh"
      - "-c"
      - |
        apk update && apk add rsync
        sleep infinity
    volumeMounts:
    - name: code-volume
      mountPath: /opt/code
  volumes:
  - name: code-volume
    emptyDir: {}  # Se puede cambiar por otro tipo de volumen según las necesidades

