#!/bin/bash

# Comprobar si se proporcionó un directorio como argumento
if [ $# -ne 1 ]; then
    echo "Usage: $0 <directory>"
    exit 1
fi

# Directorio a monitorear
directory="$1"

echo "Monitoring directory: $directory"

/Volumes/DataJack/Jack/multims/krsync -av -r --delete --progress --stats "$directory" ssh-pod:/home

# Definir la función para refrescar la sincronización
function refresh {
    echo "Starting synchronization loop..."
    # Bucle infinito
    while true; do
        # Utilizar fswatch para monitorear cambios en el directorio especificado
        echo "Waiting for changes in $directory..."
        if ! command -v fswatch &> /dev/null; then
            echo "Error: fswatch is not installed. Please install it to continue."
            exit 1
        fi

        fswatch -0 -r "$directory" | while read -d "" event; do
            echo "Change detected: $event"
            # Cuando se detecte un cambio, ejecutar rsync
            echo "Synchronizing $directory with ssh-pod:/home..."
            if ! /Volumes/DataJack/Jack/multims/krsync -av -r --delete --progress --stats "$directory" ssh-pod:/home; then
                echo "Error: Failed to synchronize $directory with ssh-pod:/home."
            else
                echo "Synchronization completed."
            fi
        done

        # Esperar 5 segundos antes de la próxima ejecución
        echo "Waiting for 5 seconds before the next check..."
        sleep 5
    done
}

# Ejecutar la función de refresco
refresh
