#!/bin/bash

# Comprobar si se proporcionaron suficientes argumentos
if [ $# -ne 3 ]; then
    echo "Usage: $0 <directory> <podname>"
    exit 1
fi

# Asignar argumentos a variables claras
directory="$1"
podname="$2"
namespace="$3"

#/Volumes/DataJack/Jack/multims/krsync -av -r --delete --progress --stats "$directory" "${podname}@${namespace}:/home"

# Obtener el directorio donde reside el script
script_dir=$(dirname "$0")
# Excluir directorios específicos del proceso de sincronización
excluded_dirs="--exclude='node_modules' --exclude='.multims'"
script_dir_abs=$(cd "$script_dir" && pwd)

echo "Monitoring directory: $directory and synchronizing with pod: $podname"

# Utilizar ruta relativa para krsync
krsync_path="/opt/homebrew/etc/multims/scripts/krsync"
echo '$krsync_path -av -r --delete --progress --stats "$directory" "${podname}@${namespace}:/home"'
$krsync_path -av -r --delete --progress --stats $excluded_dirs  "$directory" "${podname}@${namespace}:/home"

