name: Tag, Build and Release

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.get_last_tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Obtener el último tag
        id: get_last_tag
        run: |
          git fetch --tags
          last_tag=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$last_tag" ]; then
            last_tag="v1.5.0"
          fi
          IFS='.' read -r -a parts <<< "${last_tag/v/}"
          patch=$((parts[2] + 1))
          new_tag="v${parts[0]}.${parts[1]}.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "::set-output name=new_tag::$new_tag"

      - name: Build and Test
        run: |
          go build ./...
          go test ./...

      - name: Create and Push Tag
        if: ${{ steps.get_last_tag.outputs.new_tag != '' }}
        run: |
          git config --global user.name "JACKT72xp"
          git config --global user.email "JACKT72xp@users.noreply.github.com"
          git tag ${{ env.new_tag }}
          git push https://$GITHUB_ACTOR:${{ secrets.PAT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git ${{ env.new_tag }}

  release:
    needs: tag_and_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
  
      - name: Install dependencies
        run: |
          go mod download
          go mod tidy
  
      - name: Build binary
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/multims_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Generate SHA256 Checksums
        id: generate_sha256
        run: |
          sha256sum build/* > sha256sums.txt
          cat sha256sums.txt

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: multims-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/multims_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print SHA256 for copying
        run: |
          sha256_darwin_amd64=$(grep multims_darwin_amd64 sha256sums.txt | awk '{ print $1 }')
          sha256_darwin_arm64=$(grep multims_darwin_arm64 sha256sums.txt | awk '{ print $1 }')
          sha256_linux_amd64=$(grep multims_linux_amd64 sha256sums.txt | awk '{ print $1 }')
          sha256_linux_arm64=$(grep multims_linux_arm64 sha256sums.txt | awk '{ print $1 }')
    
          echo "SHA256 for multims_darwin_amd64: $sha256_darwin_amd64"
          echo "SHA256 for multims_darwin_arm64: $sha256_darwin_arm64"
          echo "SHA256 for multims_linux_amd64: $sha256_linux_amd64"
          echo "SHA256 for multims_linux_arm64: $sha256_linux_arm64"