name: Tag, Build and Release

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Obtener el último tag
        id: get_last_tag
        run: |
          # Obtener el último tag o empezar desde v1.4.0
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.4.0")
          
          # Dividir el tag en partes
          IFS='.' read -r -a parts <<< "${last_tag/v/}"
          
          # Incrementar la versión del parche
          patch=$((parts[2] + 1))
          new_tag="v${parts[0]}.${parts[1]}.$patch"
          
          # Verificar si el tag ya existe en el remoto
          if git rev-parse "refs/tags/$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists. Skipping tag creation."
            exit 0
          fi
      
          echo "New tag to create: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Build and Test
        run: |
          # Realiza el build y las pruebas
          go build ./...
          go test ./...

      - name: Create and Push Tag
        if: steps.get_last_tag.outputs.new_tag != ''
        run: |
          # Configurar git para usar el GITHUB_TOKEN
          git config --global user.name "JACKT72xp"
          git config --global user.email "JACKT72xp@users.noreply.github.com"
          
          # Crear un nuevo tag
          git tag ${{ steps.get_last_tag.outputs.new_tag }}
          
          # Subir el nuevo tag
          git push https://$GITHUB_ACTOR:${{ secrets.PAT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git ${{ steps.get_last_tag.outputs.new_tag }}
      
          echo "New tag created: ${{ steps.get_last_tag.outputs.new_tag }}"

  release:
    needs: tag_and_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necesario para obtener los tags
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
  
      - name: Install dependencies
        run: go mod download
  
      - name: Build binary
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/multims_${{ matrix.goos }}_${{ matrix.goarch }}
  
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: multims-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/multims_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_last_tag.outputs.new_tag }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}