name: Tag, Build and Release

on:
  push:
    branches:
      - master
env:
  BASE_VERSION: "v1.6.48" 
  
jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.get_last_tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Create and Push Tag
        id: push_tag
        run: |
          git config --global user.name "JACKT72xp"
          git config --global user.email "JACKT72xp@users.noreply.github.com"
          git tag ${{ env.BASE_VERSION }}
          git push https://$GITHUB_ACTOR:${{ secrets.PAT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git ${{ env.BASE_VERSION }}

  build_linux:
    needs: tag_and_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build binary for Linux
        run: |
          mkdir -p build
          GOOS=linux GOARCH=${{ matrix.goarch }} go build -o build/multims_linux_${{ matrix.goarch }}

      - name: Generate SHA256 Checksums for Linux
        run: |
          sha256sum build/* > sha256sums_linux.txt
          cat sha256sums_linux.txt

      - name: Upload Linux binaries
        uses: actions/upload-artifact@v3
        with:
          name: multims-linux-${{ matrix.goarch }}
          path: build/multims_linux_${{ matrix.goarch }}

  build_macos:
    needs: tag_and_release
    runs-on: macos-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build binary for macOS
        run: |
          mkdir -p build
          GOOS=darwin GOARCH=${{ matrix.goarch }} go build -o build/multims_darwin_${{ matrix.goarch }}

      - name: Generate SHA256 Checksums for macOS
        run: |
          shasum -a 256 build/* > sha256sums_macos.txt
          cat sha256sums_macos.txt

      - name: Upload macOS binaries
        uses: actions/upload-artifact@v3
        with:
          name: multims-macos-${{ matrix.goarch }}
          path: build/multims_darwin_${{ matrix.goarch }}

  release:
    needs: [tag_and_release, build_linux, build_macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: multims-linux-amd64
          path: build/
      - uses: actions/download-artifact@v3
        with:
          name: multims-linux-arm64
          path: build/
      - uses: actions/download-artifact@v3
        with:
          name: multims-macos-amd64
          path: build/
      - uses: actions/download-artifact@v3
        with:
          name: multims-macos-arm64
          path: build/

      - name: Generate SHA256 Checksums for all binaries
        run: |
          sha256sum build/* > sha256sums.txt
          cat sha256sums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BASE_VERSION }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Print SHA256 for copying
        run: |
          sha256_darwin_amd64=$(grep multims_darwin_amd64 sha256sums.txt | awk '{ print $1 }')
          sha256_darwin_arm64=$(grep multims_darwin_arm64 sha256sums.txt | awk '{ print $1 }')
          sha256_linux_amd64=$(grep multims_linux_amd64 sha256sums.txt | awk '{ print $1 }')
          sha256_linux_arm64=$(grep multims_linux_arm64 sha256sums.txt | awk '{ print $1 }')
    
          echo "SHA256 for multims_darwin_amd64: $sha256_darwin_amd64"
          echo "SHA256 for multims_darwin_arm64: $sha256_darwin_arm64"
          echo "SHA256 for multims_linux_amd64: $sha256_linux_amd64"
          echo "SHA256 for multims_linux_arm64: $sha256_linux_arm64"